# Generated by Django 3.2.12 on 2022-02-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_district_restaurant_restaurantfooderna_restaurantfoodthris_restaurantfoodtrivan'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('quantity', models.TextField()),
                ('phone', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
